var sampleCards = [
    {
        grpid: 6873,
        titleId: 2929,
        artId: 1837,
        isToken: false,
        isCollectible: false,
        isCraftable: false,
        artSize: 0,
        power: 8,
        toughness: 4,
        flavorId: 431065,
        CollectorNumber: '210',
        altDeckLimit: null,
        cmc: 8,
        rarity: 2,
        artistCredit: 'Steve White',
        set: 'MIR',
        linkedFaceType: 0,
        types: [2],
        subtypes: [55],
        supertypes: [],
        cardTypeTextId: 8,
        subtypeTextId: 738,
        colors: [5],
        frameColors: [5],
        frameDetails: [],
        colorIdentity: [5],
        abilities: [
            {
                abilityId: 14,
                textId: 28
            }
        ],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o6oGoG',
        linkedTokens: [],
        knownSupportedStyles: [],
        DigitalReleaseSet: ''
    },
    {
        grpid: 6993,
        titleId: 647,
        artId: 1897,
        isToken: false,
        isCollectible: true,
        isCraftable: false,
        artSize: 0,
        power: 0,
        toughness: 0,
        flavorId: 1,
        CollectorNumber: '347',
        altDeckLimit: 250,
        cmc: 0,
        rarity: 1,
        artistCredit: 'Tony Roberts',
        set: 'MIR',
        linkedFaceType: 0,
        types: [5],
        subtypes: [29],
        supertypes: [1],
        cardTypeTextId: 261494,
        subtypeTextId: 647,
        colors: [],
        frameColors: [5],
        frameDetails: [],
        colorIdentity: [5],
        abilities: [],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o0',
        linkedTokens: [],
        knownSupportedStyles: [],
        DigitalReleaseSet: ''
    },
    {
        grpid: 7065,
        titleId: 652,
        artId: 1933,
        isToken: false,
        isCollectible: true,
        isCraftable: false,
        artSize: 0,
        power: 0,
        toughness: 0,
        flavorId: 1,
        CollectorNumber: '336',
        altDeckLimit: 250,
        cmc: 0,
        rarity: 1,
        artistCredit: 'Douglas Shuler',
        set: 'MIR',
        linkedFaceType: 0,
        types: [5],
        subtypes: [43],
        supertypes: [1],
        cardTypeTextId: 261494,
        subtypeTextId: 652,
        colors: [],
        frameColors: [2],
        frameDetails: [],
        colorIdentity: [2],
        abilities: [],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o0',
        linkedTokens: [],
        knownSupportedStyles: [],
        DigitalReleaseSet: ''
    },
    {
        grpid: 7153,
        titleId: 1250,
        artId: 1977,
        isToken: false,
        isCollectible: true,
        isCraftable: false,
        artSize: 0,
        power: 0,
        toughness: 0,
        flavorId: 1,
        CollectorNumber: '346',
        altDeckLimit: 250,
        cmc: 0,
        rarity: 1,
        artistCredit: 'John Avon',
        set: 'MIR',
        linkedFaceType: 0,
        types: [5],
        subtypes: [49],
        supertypes: [1],
        cardTypeTextId: 261494,
        subtypeTextId: 1250,
        colors: [],
        frameColors: [4],
        frameDetails: [],
        colorIdentity: [4],
        abilities: [],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o0',
        linkedTokens: [],
        knownSupportedStyles: [],
        DigitalReleaseSet: ''
    },
    {
        grpid: 7193,
        titleId: 648,
        artId: 1997,
        isToken: false,
        isCollectible: true,
        isCraftable: false,
        artSize: 0,
        power: 0,
        toughness: 0,
        flavorId: 1,
        CollectorNumber: '331',
        altDeckLimit: 250,
        cmc: 0,
        rarity: 1,
        artistCredit: 'Tom Wänerstrand',
        set: 'MIR',
        linkedFaceType: 0,
        types: [5],
        subtypes: [54],
        supertypes: [1],
        cardTypeTextId: 261494,
        subtypeTextId: 648,
        colors: [],
        frameColors: [1],
        frameDetails: [],
        colorIdentity: [1],
        abilities: [],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o0',
        linkedTokens: [],
        knownSupportedStyles: [],
        DigitalReleaseSet: ''
    },
    {
        grpid: 7347,
        titleId: 653,
        artId: 2074,
        isToken: false,
        isCollectible: true,
        isCraftable: false,
        artSize: 0,
        power: 0,
        toughness: 0,
        flavorId: 1,
        CollectorNumber: '340',
        altDeckLimit: 250,
        cmc: 0,
        rarity: 1,
        artistCredit: 'Bob Eggleton',
        set: 'MIR',
        linkedFaceType: 0,
        types: [5],
        subtypes: [69],
        supertypes: [1],
        cardTypeTextId: 261494,
        subtypeTextId: 653,
        colors: [],
        frameColors: [3],
        frameDetails: [],
        colorIdentity: [3],
        abilities: [],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o0',
        linkedTokens: [],
        knownSupportedStyles: [],
        DigitalReleaseSet: ''
    },
    {
        grpid: 9135,
        titleId: 4446,
        artId: 2788,
        isToken: false,
        isCollectible: true,
        isCraftable: true,
        artSize: 0,
        power: 0,
        toughness: 0,
        flavorId: 1,
        CollectorNumber: '153',
        altDeckLimit: null,
        cmc: 2,
        rarity: 2,
        artistCredit: 'Adam Rex',
        set: 'WTH',
        linkedFaceType: 0,
        types: [1],
        subtypes: [],
        supertypes: [],
        cardTypeTextId: 7,
        subtypeTextId: 0,
        colors: [],
        frameColors: [],
        frameDetails: [],
        colorIdentity: [],
        abilities: [
            {
                abilityId: 1152,
                textId: 227595
            },
            {
                abilityId: 88188,
                textId: 281939
            }
        ],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o2',
        linkedTokens: [],
        knownSupportedStyles: ['DA'],
        DigitalReleaseSet: 'AHA1'
    },
    {
        grpid: 14717,
        titleId: 16473,
        artId: 25145,
        isToken: false,
        isCollectible: true,
        isCraftable: true,
        artSize: 0,
        power: 2,
        toughness: 2,
        flavorId: 16474,
        CollectorNumber: '237',
        altDeckLimit: null,
        cmc: 4,
        rarity: 4,
        artistCredit: 'Ray Lago',
        set: 'INV',
        linkedFaceType: 0,
        types: [2],
        subtypes: [39, 64],
        supertypes: [2],
        cardTypeTextId: 261554,
        subtypeTextId: 50231,
        colors: [5, 1],
        frameColors: [5, 1],
        frameDetails: [],
        colorIdentity: [5, 1],
        abilities: [
            {
                abilityId: 6371,
                textId: 16475
            }
        ],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o2oGoW',
        linkedTokens: [],
        knownSupportedStyles: ['DA'],
        DigitalReleaseSet: 'AHA1'
    },
    {
        grpid: 15281,
        titleId: 29459,
        artId: 27998,
        isToken: false,
        isCollectible: false,
        isCraftable: false,
        artSize: 0,
        power: 5,
        toughness: 5,
        flavorId: 29460,
        CollectorNumber: '135',
        altDeckLimit: null,
        cmc: 10,
        rarity: 3,
        artistCredit: 'Brian Snoddy',
        set: 'PLS',
        linkedFaceType: 0,
        types: [1, 2],
        subtypes: [10],
        supertypes: [],
        cardTypeTextId: 261533,
        subtypeTextId: 325,
        colors: [],
        frameColors: [],
        frameDetails: [],
        colorIdentity: [],
        abilities: [
            {
                abilityId: 128228,
                textId: 310319
            },
            {
                abilityId: 14,
                textId: 28
            }
        ],
        hiddenAbilities: [],
        linkedFaces: [],
        castingcost: 'o10',
        linkedTokens: [],
        knownSupportedStyles: [],
        DigitalReleaseSet: ''
    }
];

module.exports = sampleCards;
